# This entrypoint file to be used in development. Start by reading README.md
import shape_calculator
width = input("Enter the width of your rectangle: ")
height = input("Enter the height of your rectangle: ")
rect = shape_calculator.Rectangle(int(width), int(height))
print()
print(rect)
print("Area: " + str(rect.get_area()))
print("Perimeter: " + str(rect.get_perimeter()))
print("Diagonal: " + str(round(rect.get_diagonal(), 2)))
print()
print(rect.get_picture())
print()
change = input("Would you like to adjust the width/height of your reactangle? (True/False) ")

if(change == "True"):
  width = input("Enter the new width of your rectangle: ")
  height = input("Enter the new height of your rectangle: ")
  rect.set_height(int(height))
  rect.set_width(int(width))
  print()
  print(rect)
  print("Area: " + str(rect.get_area()))
  print("Perimeter: " + str(rect.get_perimeter()))
  print("Diagonal: " + str(round(rect.get_diagonal(), 2)))
  print()
  print(rect.get_picture())

length = input("Enter the side length for your square: ")
sq = shape_calculator.Square(int(length))
print()
print(sq)
print("Area (Square): " + str(round(sq.get_area(), 2)))
print("Perimeter (Square): " + str(sq.get_perimeter()))
print("Diagonal (Square): " + str(round(sq.get_diagonal(), 2)))
print()
print(sq.get_picture())
print("Your " + str(sq) + " could fit in your " + str(rect) + " " + str(rect.get_amount_inside(sq)) + " times!")

